### ISSUE TITLE
Please close this repository

### ISSUE THREAD

**Issue by ghost** [sortex/tcpdf#1]
This repository is out-of-sync with the official TCPDF repository located at http://sourceforge.net/projects/tcpdf and is creating confusion on many users. Please close it and join the official TCPDF developers http://www.tcpdf.org

**Comment by rafi** [comment]
:( There are endless clones of TCPDF here at Github alone.. I've added a caution description, however I can't close this repository, as it is a mandatory dependency with my apps, and has a few personal commits..

**Comment by ghost** [comment]
Why don't you sync you project with the official TCPDF git repository at sourceforge and add your contributions there? What's the point of having multiple forks of the same project? Don't you think it is better if your contributions goes on the main release?
